services:
  valkey:
    image: valkey/valkey
    ports:
      - 6379:6379
    volumes:
      - valkey_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/qdrant/storage

  server:
    build: ./server
    ports:
      - 8000:8000
    depends_on:
      - valkey
      - qdrant
    environment:
      - REDIS_HOST=valkey
      - REDIS_PORT=6379
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./server/uploads:/app/uploads
    command: npm run dev

  worker:
    build: ./server
    depends_on:
      - valkey
      - qdrant
    environment:
      - REDIS_HOST=valkey
      - REDIS_PORT=6379
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./server/uploads:/app/uploads
    command: npm run dev:worker

volumes:
  valkey_data:
  qdrant_data: